#!/usr/bin/env python3

# Used to collect 'genomic' bed files (containing all locations of all genes from a gene family)

import os

# This was run locally pointing to a google drive document
path_to_GFF_files = r"/Users/kxp5629/My Drive/work/PennState/Y_chromosome/Origins_selection_and_copy_number_variation_of_YAGs/Gene_copies_GFF/"

genes=["TSPY", "RBMY", "CDY", "BPY2", "HSFY", "VCY"]
species_list=["HomSap", "PanTro", "PanPan", "GorGor","PonPyg", "PonAbe"]
files= []

chr_y_contig = {'PanPan': "NC_073273.2",
                'PanTro': "NC_072422.2",
                'HomSap': "NC_060948.1",
                'GorGor': "NC_073248.2",
                'PonPyg': "NC_072397.2",
                'PonAbe': "NC_072009.2",
}

def main():
    #list all files in the directory
    for file in os.listdir(path_to_GFF_files):
        files.append(file)

    for species in species_list:
        y_chr = chr_y_contig[species]
        for gene in genes:
            sub_files = [file for file in files if gene in file and species in file]
            print(f"Files for {species} and {gene}: {sub_files}")

            if len(sub_files) == 1:
                out_file = f"{species}_{gene}_genomic_autogenerated.bed"
                with open(out_file, 'w') as out:
                    with open(f"{path_to_GFF_files}/{sub_files[0]}", 'r') as f:
                        for line in f:
                            fields = line.strip().split('\t')
                            if len(fields) > 3:
                                if fields[0] == y_chr and fields[2] == "gene":
                                    out.write(f"{fields[0]}\t{fields[3]}\t{fields[4]}\n")

                                if fields[2] == "pseudogene":
                                    print("Warning: Pseudogene found", file=sys.stderr)

if __name__ == "__main__":
    main()
